"""modify notifications

Revision ID: 4b8a2167bb0a
Revises: d7998e46d925
Create Date: 2025-03-30 19:33:09.790515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b8a2167bb0a'
down_revision = 'd7998e46d925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('isRead', sa.Boolean(), nullable=True))
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('isRead')
        batch_op.drop_column('userID')

    # ### end Alembic commands ###
