"""add raspberry pi id

Revision ID: 8e9158256428
Revises: 0c34f41dadd2
Create Date: 2025-03-30 12:43:50.777288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9158256428'
down_revision = '0c34f41dadd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raspberryPiId', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['raspberryPiId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('raspberryPiId')

    # ### end Alembic commands ###
