"""Remove relation between schedule and carers

Revision ID: dd80a90f1729
Revises: 85aea1d1575f
Create Date: 2025-04-03 20:44:50.386800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd80a90f1729'
down_revision = '85aea1d1575f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pill_schedule', schema=None) as batch_op:
        batch_op.drop_constraint('pill_schedule_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('pill_schedule_ibfk_3', type_='foreignkey')
        batch_op.drop_column('caregiverID')
        batch_op.drop_column('pharmacyID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pill_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacyID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('caregiverID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pill_schedule_ibfk_3', 'pharmacy', ['pharmacyID'], ['pharmacyID'])
        batch_op.create_foreign_key('pill_schedule_ibfk_2', 'caregiver', ['caregiverID'], ['caregiverID'])

    # ### end Alembic commands ###
